twig:
    file_name_pattern: '*.twig'
    globals:
        app_name: 'NexusWeb'
        article_directory: 'uploads/article/'
        job_directory: 'uploads/job/'

when@test:
    twig:
        strict_variables: true
